import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {GraphQLClient, gql} from 'graphql-request'




const query = gql`
{
  posts {
    id,
    title,
    datePublished,
    slug,
    content {
      html
    }
    author{
      name,
      avatar {
        url
      }
    }
    coverPhoto {
      publishedAt{
        createdBy {
          id
        }
        url
      }
    }
  }
}
`;

//Fetch request
export async function getStaticProps(){
  const {post} = await graphcms.request(query);
  return{
    props: {
      posts,
    },
    revalidate: 10,
  }
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

      </main>

    
    </div>
  )
}
